# hash:sha256:3f7b3ec6e20c49a20f958c4c8f22f9f0322800e2f876f7234cccd1e6a1f279c9
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/py-r:python3.12.8-R4.4.2-JupyterLab4.3.5-RStudiorstudio-server-2024.12.1-563-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
